<?php

namespace BackupMe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApiClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiClientRepository extends EntityRepository
{
    public function getSearchApiClientResult($search,$type)
    {
        $qb = $this->createQueryBuilder('ac');
        $qb->where('ac.name LIKE :search or ac.iPAddress LIKE :search')
           ->andWhere('ac.type = :type')
           ->setParameter('search', '%'.$search.'%')
           ->setParameter('type', $type);

        return $qb->getQuery()
                  ->getResult();
    }

    public function findAllByType($type)
    {
        $qb = $this->createQueryBuilder('ac');
        $qb->where('ac.type = :type')
           ->setParameter('type', $type);

        return $qb->getQuery()
                  ->getResult();
    }
}
