<?php

namespace BackupMe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function getSearchCompanyResult($search)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.longName LIKE :search')
            ->orWhere('c.shortName LIKE :search')
                ->setParameter('search', '%'.$search.'%');

        return $qb->getQuery()
                  ->getResult();
    }
}
