<?php

namespace BackupMe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function getSearchCompanyResult($search)
    {
        $query = $this->getEntityManager()
        ->createQuery(
            'SELECT c
            FROM BackupMeMainBundle:Company c
            WHERE c.longName LIKE :search')
        ->setParameter('search', '%'.$search.'%')
        ->getResult();
    }
}
