<?php

namespace BackupMe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function getSearchContactResult($search)
    {
        $qb = $this->createQueryBuilder('cc');
        $qb->where('cc.name LIKE :search')
           ->orWhere('cc.email LIKE :search')
           ->setParameter('search', '%'.$search.'%');

        return $qb->getQuery()
                  ->getResult();
    }
}
