<?php

namespace BackupMe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends EntityRepository
{
    public function getSearchContractResult($search)
    {
        $qb = $this->createQueryBuilder('ct');
        $qb->join('ct.company', 'cp')
           ->where('ct.name LIKE :search')
           ->orWhere('cp.longName LIKE :search')
           ->setParameter('search', '%'.$search.'%');

        return $qb->getQuery()
                  ->getResult();
    }

    public function findAll()
    {
        $qb = $this->createQueryBuilder('ct');
        $qb->join('ct.company', 'cp')
           ->addOrderBy('cp.longName', 'ASC')
           ->addOrderBy('ct.name', 'ASC');

        return $qb->getQuery()
                  ->getResult();
    }
}
