<?php

namespace BackupMe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    public function getSearchLocationResult($search)
    {
        $qb = $this->createQueryBuilder('l');
        $qb->join('l.contract', 'ct')
           ->join('ct.company', 'cp')
           ->where('l.name LIKE :search')
           ->orWhere('ct.name LIKE :search')
           ->orWhere('cp.longName LIKE :search')
           ->setParameter('search', '%'.$search.'%');

        return $qb->getQuery()
                  ->getResult();
    }
}
