<?php

namespace BackupMe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleTypeRepository extends EntityRepository
{
    public function getSearchModuleTypeResult($search)
    {
        $qb = $this->createQueryBuilder('mt');
        $qb->where('mt.name LIKE :search')
           ->setParameter('search', '%'.$search.'%');

        return $qb->getQuery()
                  ->getResult();
    }
}
