<?php

namespace BackupMe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
    public function getSearchModuleResult($search)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->join('m.moduletype', 'mt')
           ->where('m.name LIKE :search')
           ->orWhere('m.description LIKE :search')
           ->orWhere('mt.name LIKE :search')
           ->setParameter('search', '%'.$search.'%');

        return $qb->getQuery()
                  ->getResult();
    }
}
